language: node_js
node_js: node # install the latest release of node
cache:
  yarn: true
  directories:
  - $HOME/.electron
  - node_modules
script:
  - script/travis-build.sh
  - script/travis-upload-build.sh
